### PR TITLE
Add Card Entities and required Enums

### PR DESCRIPTION
**Pull request by Tylerwbrown**
## Asana Link
https://app.asana.com/0/505149144121805/508641797510000
## Description
Added our first entities & enums.

This code is doing more than it seems initially (did a lot of readings on Scala, make sure to look into this stuff too).

The classes primary constructor is taking those parameters, and setting them as immutable members on the class by default because of the val keyword. For the ones that don't have the val keyword, you'll notice that they're being passed to the super class (that happens automatically via the extends call) and there, they're being instantiated automatically.

The equivalent Java code would entail defining a constructor, passing in the variables to the constructor (we did do that here), declaring immutable (final) private members, and then initializing those members in the constructor, as well as declaring getters and setters for those members.

By "equivalent", I really mean equivalent. You can compile this Scala code and decompile it into Java and that's what would be happening.

Ethan did help out here (I couldn't @ him because he might've not joined this group yet), but for the first night he was here for development of this feature, so we have at least two eyes on some of this code.

The code we both worked on was an earlier implementation of Card, Spell, and Minion. And we discussed the domain surrounding this as well, so we were fleshing out ideas before diving in.

### CODE REVIEW

**Comment by 1335draco** [comment]
This looks good to me, I just wanted some clarification on "HeroCard", is this a representation of the Hero you're playing or one of the cards that can replace your hero?

**Review by calvin-do — APPROVED** [review]
This looks good to me, I just wanted some clarification on "HeroCard", is this a representation of the Hero you're playing or one of the cards that can replace your hero?

**Comment by Tylerwbrown** [comment]
The latter, those new types of cards that came out a number of expansions ago that entirely replace your hero and their hero power.

This is different than Lord Jarraxus or Majordomo (idk how to spell either of those). Ethan and I did some digging in that field, Lord Jarraxus and Majordomo are minion cards that eventually have the effect of replacing your hero with something, the first one just happens to happen as a battlecry.

But you can randomly summon Lord Jarraxus as a demon/minion. Can't do that with normal "hero cards"

**Comment by Tylerwbrown** [comment]
Shipping

**Pull request merged**
